openapi: 3.0.0
info:
  title: Chess Game API
  description: API for managing chess games
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
paths:
  /games:
    get:
      summary: Retrieve all chess games
      operationId: getAllChessGames
      responses:
        '200':
          description: A list of chess games
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChessGame'
    post:
      summary: Create a new chess game
      operationId: createChessGame
      responses:
        '201':
          description: The created chess game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChessGame'
  /games/{id}:
    get:
      summary: Retrieve a specific chess game
      operationId: getChessGameById
      parameters:
        - name: id
          in: path
          description: ID of the chess game to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The requested chess game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChessGame'
    put:
      summary: Update a chess game
      operationId: updateChessGame
      parameters:
        - name: id
          in: path
          description: ID of the chess game to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateChessGame'
      responses:
        '200':
          description: The updated chess game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChessGame'
    delete:
      summary: Delete a chess game
      operationId: deleteChessGame
      parameters:
        - name: id
          in: path
          description: ID of the chess game to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Chess game deleted successfully

components:
  schemas:
    ChessGame:
      type: object
      properties:
        id:
          type: integer
          format: int64
        status:
          type: string
          enum: [ "in_progress", "completed" ]
        winner:
          type: string
          nullable: true
        moves:
          type: array
          items:
            type: string
    UpdateChessGame:
      type: object
      properties:
        status:
          type: string
          enum: [ "in_progress", "completed" ]
        winner:
          type: string
          nullable: true
        moves:
          type: array
          items:
            type: string